### ISSUE TITLE
Comparison with node-config

### ISSUE THREAD

**Issue by timkelty** [pilwon/node-get-config#1]
I've been using https://github.com/lorenwest/node-config for a bit, but just noticed your package.

Just wondering if you've used it and if you can offer any comparisons to how `node-get-config` works, or why you'd choose one over the other.

On the surface, I like that `node-get-config` seems a bit simpler/less-magical than `node-config`.
Also, `node-config` values are immutable, which I see the benefit of but has also caused a bit of trouble.

Thanks!

**Comment by pilwon** [comment]
@timkelty They share the same goal of simplifying config file loading, but there are some notable differences in `node-get-config`. It assumes you often require multiple config files to keep your config organized. Therefore it loads a directory rather than a single file. It also assumes you often use `NODE_ENV` to differentiate app running environment, so it supports [node-get-env](https://github.com/pilwon/node-get-env) out of box. These two design assumptions make it more suitable for larger applications as config scales with your application size.

There are some minor features such as supporting optional extensions as plugins rather than hard dependencies, and supporting both async and sync FS operations. However as you noticed this library only focuses on simple goals to keep it light and predictable. (avoiding magic)  For immutable need, you can use `Object.freeze` or an immutable library such as [Immutable-js](https://github.com/facebook/immutable-js).

**Comment by timkelty** [comment]
Thanks for the reply!
